# Generated by Django 3.0.1 on 2020-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('slotCode', models.CharField(max_length=30)),
                ('nominatedWorker', models.BooleanField()),
                ('hiringManager', models.CharField(choices=[('LC', 'Liz Catherall'), ('DAVE', 'Dave Matthews'), ('NM', 'Nitesh Malvi'), ('DEFAULT', 'Please select a hiring manager...')], default='DEFAULT', max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('projectDescription', models.TextField()),
                ('costCentreCode', models.CharField(choices=[('ST', 'Strategy - 109711'), ('T', 'Technology - 10971'), ('DIG', 'Digital - 109713'), ('DAT', 'Data - 109714'), ('DA', 'DDaT Director and Business Operations - 109715'), ('S', 'SPIRE - 109376'), ('DEFAULT', 'Please select a cost code...')], default='DEFAULT', max_length=30)),
                ('progCode', models.CharField(max_length=30)),
                ('projCode', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('DM', 'Delivery Manager'), ('PM', 'Product Manager'), ('UR', 'User Researcher'), ('DEV', 'Developer'), ('TA', 'Technical Architect'), ('DES', 'Designer'), ('UXD', 'UX Designer'), ('d', 'Please select a role...')], default='d', max_length=30)),
            ],
        ),
    ]
