# Generated by Django 3.0.1 on 2020-04-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sow', '0002_auto_20200402_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='team',
            field=models.CharField(choices=[('DEFAULT', 'DDaT / Data Team')], default='DEFAULT', max_length=30),
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sow.Role'),
        ),
    ]
