# Generated by Django 3.0.1 on 2020-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sow', '0003_auto_20200402_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='roleDescription',
            field=models.TextField(blank=True),
        ),
    ]
