# Generated by Django 3.0.1 on 2020-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sow', '0004_role_roledescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['roleName']},
        ),
        migrations.AddField(
            model_name='role',
            name='roleDeliverables',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='hiringManager',
            field=models.CharField(choices=[('1', 'option 1'), ('2', 'option 2'), ('3', 'option 3'), ('DEFAULT', 'Please select a hiring manager...')], default='DEFAULT', max_length=30),
        ),
    ]
