# Generated by Django 3.0.1 on 2020-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sow', '0005_auto_20200402_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementofwork',
            name='slotCode',
            field=models.CharField(max_length=5),
        ),
    ]
