# Generated by Django 3.0.1 on 2020-04-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sow', '0007_auto_20200403_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role_name']},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='roleDeliverable1',
            new_name='role_deliverable1',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='roleDeliverable2',
            new_name='role_deliverable2',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='roleDescription',
            new_name='role_description',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='roleName',
            new_name='role_name',
        ),
        migrations.RenameField(
            model_name='statementofwork',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='statementofwork',
            old_name='costCentreCode',
            new_name='cost_centre_code',
        ),
        migrations.RenameField(
            model_name='statementofwork',
            old_name='hiringManager',
            new_name='hiring_manager',
        ),
        migrations.RenameField(
            model_name='statementofwork',
            old_name='nominatedWorker',
            new_name='nominated_worker',
        ),
        migrations.RenameField(
            model_name='statementofwork',
            old_name='progCode',
            new_name='prog_code',
        ),
        migrations.RenameField(
            model_name='statementofwork',
            old_name='projCode',
            new_name='proj_code',
        ),
        migrations.RenameField(
            model_name='statementofwork',
            old_name='projectDescription',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='statementofwork',
            old_name='slotCode',
            new_name='slot_code',
        ),
    ]
