# Generated by Django 3.0.1 on 2020-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sow', '0009_auto_20200403_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_deliverable10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_deliverable3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_deliverable4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_deliverable5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_deliverable6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_deliverable7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_deliverable8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_deliverable9',
            field=models.TextField(blank=True),
        ),
    ]
