# Generated by Django 3.0.1 on 2020-04-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sow', '0010_auto_20200403_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentreCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HiringManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable1',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable10',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable2',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable3',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable4',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable5',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable6',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable7',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable8',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_deliverable9',
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='company_name',
            field=models.CharField(max_length=160),
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sow.Role')),
            ],
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='cost_centre_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sow.CostCentreCode'),
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='hiring_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sow.HiringManager'),
        ),
        migrations.AlterField(
            model_name='statementofwork',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sow.Team'),
        ),
    ]
